# Generated by Django 4.2.1 on 2024-10-22 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('engine_model', models.CharField(max_length=100)),
                ('engine_serial_number', models.CharField(max_length=50)),
                ('transmission_model', models.CharField(max_length=100)),
                ('transmission_serial_number', models.CharField(max_length=50)),
                ('leading_bridge_model', models.CharField(max_length=100)),
                ('leading_bridge_serial_number', models.CharField(max_length=50)),
                ('controlled_bridge_model', models.CharField(max_length=100)),
                ('controlled_bridge_serial_number', models.CharField(max_length=50)),
                ('supply_contract_number', models.CharField(max_length=50)),
                ('shipping_date', models.DateField()),
                ('recipient', models.CharField(max_length=200)),
                ('delivery_address', models.CharField(max_length=300)),
                ('configuration', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_machines', to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(limit_choices_to={'is_service': True}, on_delete=django.db.models.deletion.CASCADE, related_name='service_company_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('hours_operational', models.FloatField()),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('organization', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='silant_django_app.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_date', models.DateField()),
                ('hours_operational', models.FloatField()),
                ('failure_unit', models.CharField(max_length=100)),
                ('failure_description', models.TextField()),
                ('recovery_method', models.CharField(max_length=100)),
                ('spare_parts_used', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='silant_django_app.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
    ]
